// static svgs doesn't work for release build on Android using react-native-svg-uri
const images = {
  welcomeBackground: require('../static/welcome_background.jpg'),
  logo: require('../static/logo_coffective.png'),
  guideBackground: require('../static/guide_background.png'),
  loginBackground: require('../static/login_background.png'),
  forgotPasswordBackground: require('../static/forgot_password_background.png'),
  personTypeBackground: require('../static/person_type_background.png'),
  nameBackground: require('../static/name_background.png'),
  stateBackground: require('../static/state_background.png'),
  ageBackground: require('../static/age_background.png'),
  expectationBackground: require('../static/expectation_background.png'),
  registerBackground: require('../static/register_background.png'),
  homeBackground: require('../static/home_background.png'),
  buildTeamBackground: require('../static/build_team_background.png'),
  faqBackground: require('../static/faq_background.png'),
  checklistBackground: require('../static/checklist_background.png'),
  checklistItemBackground: require('../static/checklist_item_background.png'),
  howItWorksBackground: require('../static/how_it_works_background.png'),
  findSupportBackground: require('../static/find_support_background.png'),
  wicBackground: require('../static/wic_background.png'),
  wicImage: require('../static/wicimage.png'),
  hospitalBackground: require('../static/hospital_background.png'),
  hospital: require('../static/hospital.png'),
  championBackground: require('../static/champion_background.png'),
  champion: require('../static/champion.png'),
  expectation: {
    // birth: {uri: 'https://new.coffective.com/wp-content/uploads/2018/04/birth.svg'},
    // month1: {uri: 'https://new.coffective.com/wp-content/uploads/2018/04/1month.svg'},
    // month2: {uri: 'https://new.coffective.com/wp-content/uploads/2018/04/2month.svg'},
    // month3: {uri: 'https://new.coffective.com/wp-content/uploads/2018/04/3month.svg'},
    // month4: {uri: 'https://new.coffective.com/wp-content/uploads/2018/04/4month.svg'},
    // month5: {uri: 'https://new.coffective.com/wp-content/uploads/2018/04/5month.svg'},
    // month6: {uri: 'https://new.coffective.com/wp-content/uploads/2018/04/6month.svg'},
    // month7: {uri: 'https://new.coffective.com/wp-content/uploads/2018/04/7month.svg'},
    // month8: {uri: 'https://new.coffective.com/wp-content/uploads/2018/04/8month.svg'},
    // month9: {uri: 'https://new.coffective.com/wp-content/uploads/2018/04/9month.svg'},
    birth: require('../static/expect/birth.svg'),
    month1: require('../static/expect/1month.svg'),
    month2: require('../static/expect/2month.svg'),
    month3: require('../static/expect/3month.svg'),
    month4: require('../static/expect/4month.svg'),
    month5: require('../static/expect/5month.svg'),
    month6: require('../static/expect/6month.svg'),
    month7: require('../static/expect/7month.svg'),
    month8: require('../static/expect/8month.svg'),
    month9: require('../static/expect/9month.svg')
  },
  personTypes: {
    mother: require('../static/mother.svg'),
    parent: require('../static/parent.svg'),
    nurse: require('../static/nurse.svg'),
    friend: require('../static/friend.svg'),
    provider: require('../static/provider.svg'),
    other: require('../static/other.svg')
  },
  ages: {
    under15: {
      uri: 'https://new.coffective.com/wp-content/uploads/2018/04/under15.svg'
    },
    '16-18': require('../static/16-18.svg'),
    '18-25': require('../static/18-25.svg'),
    '25-35': require('../static/25-35.svg'),
    '35-45': require('../static/35-45.svg'),
    '50+': require('../static/50.svg')
  },
  article: {
    for_baby: require('../static/for_baby.svg'),
    for_mother: require('../static/35-45.svg'),
    for_champion: {
      uri:
        'https://new.coffective.com/wp-content/uploads/2018/04/for_champion.svg'
    }
  },
  menu: {
    home: require('../static/home-2.svg'),
    ask_questions: require('../static/ask_questions.svg'),
    build_your_team: require('../static/build_your_team.svg'),
    checklist: require('../static/checklist.svg'),
    settings: require('../static/settings.svg'),
    start_here: require('../static/start_here.svg'),
    find_support: require('../static/find_support.svg')
  },
  slideArrowLeft: require('../static/slider_arrow_left.svg'),
  slideArrowRight: require('../static/slider_arrow_right.svg'),
  states: {
    AK: require('../static/AK.svg'),
    AL: require('../static/AL.svg'),
    AR: require('../static/AR.svg'),
    AZ: require('../static/AZ.svg'),
    CA: require('../static/CA.svg'),
    CO: require('../static/CO.svg'),
    CT: require('../static/CT.svg'),
    DE: require('../static/DE.svg'),
    FL: require('../static/FL.svg'),
    GA: require('../static/GA.svg'),
    HI: require('../static/HI.svg'),
    IA: require('../static/IA.svg'),
    ID: require('../static/ID.svg'),
    IL: require('../static/IL.svg'),
    IN: require('../static/IN.svg'),
    KS: require('../static/KS.svg'),
    KY: require('../static/KY.svg'),
    LA: require('../static/LA.svg'),
    MA: require('../static/MA.svg'),
    MD: require('../static/MD.svg'),
    ME: require('../static/ME.svg'),
    MI: require('../static/MI.svg'),
    MN: require('../static/MN.svg'),
    MO: require('../static/MO.svg'),
    MS: require('../static/MS.svg'),
    MT: require('../static/MT.svg'),
    NC: require('../static/NC.svg'),
    ND: require('../static/ND.svg'),
    NE: require('../static/NE.svg'),
    NH: require('../static/NH.svg'),
    NJ: require('../static/NJ.svg'),
    NM: require('../static/NM.svg'),
    NV: require('../static/NV.svg'),
    NY: require('../static/NY.svg'),
    OH: require('../static/OH.svg'),
    OK: require('../static/OK.svg'),
    OR: require('../static/OR.svg'),
    PA: require('../static/PA.svg'),
    RI: require('../static/RI.svg'),
    SC: require('../static/SC.svg'),
    SD: require('../static/SD.svg'),
    TN: require('../static/TN.svg'),
    TX: require('../static/TX.svg'),
    UT: require('../static/UT.svg'),
    VA: require('../static/VA.svg'),
    VT: require('../static/VT.svg'),
    WA: require('../static/WA.svg'),
    WI: require('../static/WI.svg'),
    WV: require('../static/WV.svg'),
    WY: require('../static/WY.svg')
  },
  buildMyTeamBackground: require('../static/build_your_team.png'),
  checkcListBackground: require('../static/check_list.png'),
  holdeNameGradient: require('../static/holdename.png')
}

export default images
