// leave off @2x/@3x
const images = {
  backgroundVideo: require('../static/background.mp4'),
  logo: require('../static/logo_coffective.png'),
  guideBackground: require('../static/guide_background.png'),
  guide1: require('../static/guide1.png'),
  guide2: require('../static/guide2.png'),
  guide3: require('../static/guide3.png'),
  loginBackground: require('../static/login_background.png'),
  forgotPasswordBackground: require('../static/forgot_password_background.png'),
  personTypeBackground: require('../static/person_type_background.png'),
  nameBackground: require('../static/name_background.png'),
  stateBackground: require('../static/state_background.png'),
  ageBackground: require('../static/age_background.png'),
  expectationBackground: require('../static/expectation_background.png'),
  woman: require('../static/woman.png'),
  registerBackground: require('../static/register_background.png'),
  homeBackground: require('../static/home_background.png'),
  buildTeamBackground: require('../static/build_team_background.png'),
  faqBackground: require('../static/faq_background.png'),
  checklistBackground: require('../static/checklist_background.png'),
  checklistItemBackground: require('../static/checklist_item_background.png'),
  howItWorksBackground: require('../static/how_it_works_background.png'),
  findSupportBackground: require('../static/find_support_background.png'),
  wicBackground: require('../static/wic_background.png'),
  hospitalBackground: require('../static/hospital_background.png'),
  hospital: require('../static/hospital.png'),
  wic: require('../static/wic.png'),
  championBackground: require('../static/champion_background.png'),
  champion: require('../static/champion.png'),
  expectation: {
    1: require('../static/expectation/1.png'),
    2: require('../static/expectation/2.png'),
    3: require('../static/expectation/3.png'),
    4: require('../static/expectation/1.png'),
    5: require('../static/expectation/2.png'),
    6: require('../static/expectation/3.png'),
    7: require('../static/expectation/1.png'),
    8: require('../static/expectation/2.png'),
    9: require('../static/expectation/3.png'),
    10: require('../static/expectation/1.png'),
  },
  //
  mother: require('../static/figure2.png'),
  doctor: require('../static/figure3.png'),
  father: require('../static/figure1.png'),
  arrowDown: require('../static/arrow.png'),
  personTypes: {
    mother: require('../static/person_types/mom.svg'),
    parent: require('../static/person_types/parent.svg'),
    nurse: require('../static/person_types/nurse.svg'),
    friend: require('../static/person_types/friend.svg'),
    provider: require('../static/person_types/provider.svg'),
    other: require('../static/person_types/other.svg'),
  },
  article: {
    for_baby: require('../static/article/for_baby.svg'),
    for_mother: require('../static/article/for_mother.svg'),
    for_champion: require('../static/article/for_champion.svg'),
  },
}

export default images
