// leave off @2x/@3x
const images = {
  backgroundVideo: require('../static/background.mp4'),
  logo: require('../static/logo_coffective.png'),
  guideBackground: require('../static/guide_background.png'),
  guide1: require('../static/guide1.png'),
  guide2: require('../static/guide2.png'),
  guide3: require('../static/guide3.png'),
  loginBackground: require('../static/login_background.png'),
  forgotPasswordBackground: require('../static/forgot_password_background.png'),
  personTypeBackground: require('../static/person_type_background.png'),
  nameBackground: require('../static/name_background.png'),
  stateBackground: require('../static/state_background.png'),
  ageBackground: require('../static/age_background.png'),
  expectationBackground: require('../static/expectation_background.png'),
  woman: require('../static/woman.png'),
  registerBackground: require('../static/register_background.png'),
  homeBackground: require('../static/home_background.png'),
  buildTeamBackground: require('../static/build_team_background.png'),
  faqBackground: require('../static/faq_background.png'),
  checklistBackground: require('../static/checklist_background.png'),
  howItWorksBackground: require('../static/how_it_works_background.png'),
  findSupportBackground: require('../static/find_support_background.png'),
  expectation: {
    1: require('../static/expectation/1.png'),
    2: require('../static/expectation/2.png'),
    3: require('../static/expectation/3.png'),
    4: require('../static/expectation/1.png'),
    5: require('../static/expectation/2.png'),
    6: require('../static/expectation/3.png'),
    7: require('../static/expectation/1.png'),
    8: require('../static/expectation/2.png'),
    9: require('../static/expectation/3.png'),
    10: require('../static/expectation/1.png'),
  },
  //
  mother: require('../static/figure2.png'),
  doctor: require('../static/figure3.png'),
  father: require('../static/figure1.png'),
  arrowDown: require('../static/arrow.png'),
}

export default images
