# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'coffectiveTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for coffectiveTest

  target 'coffectiveTest-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'coffectiveTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'coffectiveTest-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for coffectiveTest-tvOS

  target 'coffectiveTest-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
